#!/bin/sh

view_cleanup_dir() {
find . -type f -maxdepth 1 -exec sed 's/^<\w.*\w>.*\n//g' {} \;
find . -type f -maxdepth 1 -exec sed 's/^[^aA-zZ]$//g' {} \;
find . -type f -maxdepth 1 -exec sed 's/^[aA-zZ]$//' {} \;
find . -type f -maxdepth 1 -exec sed 's/^[<]\w*\w[>].\+$//' {} \;
find . -type f -maxdepth 1 -exec sed 's/^[aA-zZ][aA-zZ]$//' {} \;
}
view_cleanup_dir
