#!/bin/sh

message="${1:-"<- ran script"}"
level="${2:-"<- INFO"}"
script_name="$(basename $0)"
timestamp=$(date -u +"%Y-%m-%d %H:%M")
log_entry="[$timestamp] [$level] $script_name - $message"
log_file="/var/log/messages"

function loggerd() {
	printf "%s\n" "$log_entry" >> "$log_file" 
}
loggerd
