#!/bin/sh

# Access files by symlinking to sandbox
clear

# Verify if a-shell or ish
home_dir="/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/sharedlocal/home" 
asci_colors="$home_dir/.local/share/themes/terminal_graphics/.asci_colors"
logger="$home_dir/.local/xdg_config_home/logger_a-Shell"
log_file="$home_dir/.local/xdg_state_home/logs/a-Shell_logs/a-Shell_logs"
. "$logger" "Symlink manager" "INFO"
. "$asci_colors"

symlink_aShell() {
	for files in .profile .ssh .vim .vimrc; do
		ln -sf "$home_dir/$files" "$HOME/Documents" && echo "[INFO] Symlinked $files"
	done
}

# Main Logic
center "a-Shell"
header
symlink_aShell
