#!/bin/sh

# TODO Add what are actions in output

global_configs="~/Documents/.gitconfig"
home_dir="/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/sharedlocal/home"
logger="$home_dir/.local/xdg_config_home/a-Shell_logger"
pri_key="$ssh_dir/id_ed25519"
. $logger "Add git config" INFO

user_configs() {
	lg2 config user.identityFile "$pri_key"
	lg2 config user.password ""
	lg2 config user.name "VanYoshiko"
	lg2 config user.email "khorihenry@hotmail.com"
	echo "[INFO] Local user configs..."
}

create_global_configs() {
printf "[core]\n\tbare = false\n\trepositoryformatversion = 0\n\t filemode = true\n\t precomposeunicode = true\n\t logallrefupdates = true\n[user]\n\t name = VanYoshiko\n\t email = khorihenry@hotmail.com\n\t password = """"\n\t identityFile = ~/Documents/.ssh/id_ed25519\n[remote ""origin""]\n\t url = https://github.com/VanYoshiko/Irok-OS.git\n\t fetch = +refs/heads/*:refs/remotes/origin/*\n\t" > $global_configs && echo "[INFO] Github global configs created"
}

# Main:
create_user_configs
create_global_configs
