#!/bin/sh

message="${1:-"Logged script"}"
level="${2:-"INFO"}"
script_name="$(basename $0)"
timestamp=$(date -u +"%Y-%m-%d %H:%M")
log_file="/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/sharedlocal/home/.local/xdg_state_home/logs/a-Shell_logs/a-Shell_logs"

loggerd() {
	local log_entry="[$timestamp] [$level] $script_name - $message"
	printf "%s\n" "$log_entry" >> "$log_file"
}

loggerd
